### ISSUE TITLE
Host Time clock dropping pulses

### ISSUE THREAD

**Issue by JustMog** [DISTRHO/Cardinal#104]
using vst2, both synth and effect versions, with bitwig 4 on windows 10.

the missing pulses seem random, although the bpm does seem to affect the frequency of it occurring.
changing the bpm during playback fixes the problem, but stopping and resuming playback causes it to return.

possibly a separate bug, but creating more than one host time module causes even stranger behaviour.

**Comment by falkTX** [comment]
Yeah I noticed something is a little off in there.
Nice to confirm it is not just me, thanks.

if having 2 of such modules makes the clock more erratic, I kinda suspect what I am doing wrong then..

**Comment by falkTX** [comment]
Should be fixed in 1a2c64309bb822515b386a9ac9066023c95d4359
Confirmation would be greatly appreciated

**Comment by falkTX** [comment]
leaving a note for testing: on 120BPM 4/4, the 3:1 beat is skipped (so the beat number 9).
100% reproducible here.

**Comment by JustMog** [comment]
I'm still having the same issue in the latest version (22.07) unfortunately.
110bpm 4/4 for an example that reliably and frequently drops pulses for me (on step output, haven't noticed problems with beat or bar)

**Comment by falkTX** [comment]
ok will reopen then.

we found some issues on how bitwig reports time to plugins, it has rounding errors on a few values so I suspect this is another side-effect from that.

**Comment by falkTX** [comment]
@JustMog very likely fixed for real now with f9841bb333a5f7b013c89a326649a15749469b19
Testing the CI/action builds (once available) would be greatly appreciated!

**Comment by dromer** [comment]
@JustMog can you please confirm this issue with the latest release?

Otherwise we may assume this is now resolved.

**Comment by JustMog** [comment]
ah, sorry about that. yep, all seems fine. thanks!

**Comment by dromer** [comment]
thank you!
