### ISSUE TITLE
Resources do not get linked into plugins

### ISSUE THREAD

**Issue by magnetophon** [DISTRHO/Cardinal#151]
When I run a regular install, for some reason the resources do not get linked into the plugins, IOW, it looks like [these lines](https://github.com/DISTRHO/Cardinal/blob/main/Makefile#L287-L297) are not ran.
The plugins do not have a ``resources`` nor a ``Resources`` directory in them.

[The lines before](https://github.com/DISTRHO/Cardinal/blob/main/Makefile#L281-L285) are ran, or at least, the files end up where I expect them.

Here is the relevant part of the build log: https://pastebin.com/serdxzQy

**Comment by falkTX** [comment]
You are building from source? Then just import https://github.com/DISTRHO/Cardinal/commit/13e9ef37c5dd35d77a54b1cb006767be7a72ac69.patch
The source release tar has a bug, yeah.
I didn't consider it important enough for a 22.02.1 release, since if building from source you can just import the fix.

**Comment by falkTX** [comment]
btw, after successful packaging please update this wiki page https://github.com/DISTRHO/Cardinal/wiki/Install
thanks

**Comment by magnetophon** [comment]
Yes, it works now: https://github.com/NixOS/nixpkgs/pull/160488
I'll update the wiki when the PR is merged.

**Comment by falkTX** [comment]
btw, why not use the source tarball? there is a cardinal-22.02.tar.xz attached to the release tag.
that way you dont have to deal with any git submodules.

**Comment by magnetophon** [comment]
I updated the PR, thanks.

**Comment by falkTX** [comment]
Well, it is still not quite correct.
None of the submodule stuff that is in there is needed when using the tarball.
Also `src/Rack/dep/nanovg` is never used.

**Comment by magnetophon** [comment]
Ah, yes, fixed now.
That cleans it right up!
