### ISSUE TITLE
Cardinal Host Time

### ISSUE THREAD

**Issue by steveparkerdj** [DISTRHO/Cardinal#283]
Hi, Cardinal Host time is not working , i mean it counts the time signature but it doesn't send any CV or respond to start stop reset etc
ableton mac catalina AU
thanks

**Comment by falkTX** [comment]
that might be due JUCE7 breaking the time related APIs, we need to switch to JUCE6 for the AU build.

**Comment by steveparkerdj** [comment]
i don't know exactly what it means im not into coding but thanks 
keep the great work

**Comment by falkTX** [comment]
should be fixed in latest builds, like https://github.com/DISTRHO/Cardinal/actions/runs/2624134841
please confirm when you can, thanks

**Comment by steveparkerdj** [comment]
Yes all good now. 
I don't know if ...I should mention here but terrorform is not fixed, maybe shouldnt supposed to be in this file you sent me , so anyway thanks so much.

**Comment by falkTX** [comment]
thanks for confirmation, will close ticket then.

and yeah, if there was nothing mentioned on the other ticket, it likely still happens.
one thing at a time...
