### ISSUE TITLE
Missing entry method in VST2 plugin

### ISSUE THREAD

**Issue by sc3sc3** [DISTRHO/Cardinal#48]
Since awhile I cannot load the vst files anymore, they don't appear in Ardour nor in Bitwig.

Ardour info scanning:
_[Info]: Scanning: /home/sn/.vst/CardinalFX.vst/CardinalFX.so
[ERROR]: Missing entry method in VST2 plugin '/home/sn/.vst/CardinalFX.vst/CardinalFX.so'
[WARNING]: Cannot open VST2 module '/home/sn/.vst/CardinalFX.vst/CardinalFX.so'
Scan Failed.

[Info]: Scanning: /home/sn/.vst/CardinalSynth.vst/CardinalSynth.so
[ERROR]: Missing entry method in VST2 plugin '/home/sn/.vst/CardinalSynth.vst/CardinalSynth.so'
[WARNING]: Cannot open VST2 module '/home/sn/.vst/CardinalSynth.vst/CardinalSynth.so'
Scan Failed.

[Info]: Scanning: /home/sn/.vst/Cardinal.vst/Cardinal.so
[WARNING]: Cannot open VST2 module '/home/sn/.vst/Cardinal.vst/Cardinal.so'
Scan Failed._

If I remember correctly this started happening around the time Cardinal got renamed to CardinalFX

**Comment by sc3sc3** [comment]
Also vst3 and lv2 are not recognized by Ardour.

I'm on UbuntuStudio LTS 20.04

**Comment by falkTX** [comment]
delete those files and do a full rebuild. this is 99% sure an issue with your build or setup.

**Comment by sc3sc3** [comment]
I haven't been building the plugins myself, I have always used Github builds, provided under the Actions tab.

**Comment by falkTX** [comment]
Oh, interesting. I havent tried those in a while. Nevermind my last comment then, obviously invalid.

One thing that I did change was bumping from Ubuntu 18.04 base to 20.04 base.
But since you run 20.04 yourself, this should not be the problem.
So, dont know what is going on yet. If you find something please post about it.

**Comment by sc3sc3** [comment]
I got the project building succesfully, but at the end there is no bin folder.
What are the commands to build the actual vst, vst3, lv2 files?
Thanks

**Comment by sc3sc3** [comment]
Apparently I do get an error:

_Compiling src/ApplicationPrivateData.cpp
In file included from src/ApplicationPrivateData.cpp:20:
src/pugl.hpp:44:10: fatal error: pugl-upstream/include/pugl/pugl.h: No such file or directory
   44 | #include "pugl-upstream/include/pugl/pugl.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
connected.
make[1]: *** [Makefile:169: ../build/dgl/ApplicationPrivateData.cpp.o] Error 1_

**Comment by falkTX** [comment]
you need submodules

**Comment by falkTX** [comment]
anyhow I think I found the reason why.
latest commit about CardinalFX should fix it, but you need to remove Cardinal.vst which does nothing and is not possible in VST2

**Comment by sc3sc3** [comment]
concerning the submodules, I get the pugl issue with the following

https://github.com/DISTRHO/Cardinal.git
cd Cardinal
git submodule init
git submodule sync 
git submodule update 
make WITH_LTO=true -j6

**Comment by sc3sc3** [comment]
I tried the latest Actions build, and unfortunately the issue is still there: Missing entry method in VST2 plugin

**Comment by falkTX** [comment]
Yes I can reproduce that here, investigating.
Also, LTO takes a really long time, I dont recommend it for testing builds yourself.
For submodules you need to apply it recursively, aka `git submodule update --init --recursive`

**Comment by sc3sc3** [comment]
Thank you, I got the project fully built now.
Weirdly, my own built CardinalFX/CardinalSynth vst2 plugins aren't recognized either.

The standalone applications Cardinal, CardinalFX and CardinalSynth in bin folder work correctly.

**Comment by falkTX** [comment]
It is likely related to LTO.
Since you had a partial LTO build, the compiler likely tried to do a full LTO build in the end. Try `make clean` and building again without LTO.

**Comment by sc3sc3** [comment]
With clean build:
- lv2 works correctly in Ardour
-  vst2 is not seen in Ardour, nor Bitwig
-  vst3 loads but does not contain any modules to load

**Comment by falkTX** [comment]
Issue was the `-fwhole-program` that doesnt work with GCC for plugins.
